### PR TITLE
Added Fix for parsing Date issue in IE<9 for Timeline chart

### PR DESCRIPTION
**Pull request by vijayamaharaja**

### CODE REVIEW

**Comment by tshaddix** [comment]
Nice, thanks for adding the compressed version. I see that you used UTC dates. I think we need to use timezone specific methods like `setFullYear()` instead of `setUTCFullYear()`.

**Comment by vijayamaharaja** [comment]
I guess both can be used.. Am pretty sure for timeline there won't be a huge impact on time zone specification though.

**Comment by vijayamaharaja** [comment]
I used UTC specific because when I checked raw data in IE's console, the way dates are parsed were in UTC timezone.

**Comment by tshaddix** [comment]
Okay, good to know! I tried the new _parseDate function in jsfiddle, and it produced a day behind because I'm in California. I modified your code to this:

``` js
 var _parseDate = function(val){
    val = val.split('-');
    var newDate = new Date();
    newDate.setFullYear(val[0], val[1]-1, val[2]);
    newDate.setHours(0,0,0,0);
    return newDate;
};
```

And it is working without problems in chrome. Does changing parseDate to this work in IE as expected?

**Comment by vijayamaharaja** [comment]
Oh yes.. I forgot about that. I live in UK and I didn't had any changes in my timeline.

I have tested by using `setFullYear` and `setHours` and its working fine from my side. :o)

**Comment by tshaddix** [comment]
That explains it! :)

Let me know when you make those changes and we will merge!

**Comment by vijayamaharaja** [comment]
I have updated them with correct timezone functions @tshaddix .. Do your magic :o)

**Comment by tshaddix** [comment]
Awesome, looks great!

**Pull request merged**
